// <auto-generated />
using System;
using MEAI_GPT_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEAI_GPT_API.Migrations
{
    [DbContext(typeof(ConversationDbContext))]
    partial class ConversationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("MEAI_GPT_API.Models.ConversationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerEmbeddingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CorrectedAnswer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FollowUpToId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenerationModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFromCorrection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamedEntitiesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Plant")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionEmbeddingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelevantChunksCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("TopicTag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasAppreciated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ConversationEntry_CreatedAt");

                    b.HasIndex("FollowUpToId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_ConversationEntry_SessionId");

                    b.HasIndex("TopicTag")
                        .HasDatabaseName("IX_ConversationEntry_Topic");

                    b.HasIndex("WasAppreciated")
                        .HasDatabaseName("IX_ConversationEntry_Appreciated");

                    b.HasIndex("GenerationModel", "EmbeddingModel")
                        .HasDatabaseName("IX_ConversationEntry_Models");

                    b.HasIndex("SessionId", "CreatedAt")
                        .HasDatabaseName("IX_ConversationEntry_Session_Time");

                    b.ToTable("ConversationEntries");
                });

            modelBuilder.Entity("MEAI_GPT_API.Models.ConversationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConversationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTopicAnchor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTopicTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPlant")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastAccessedAt")
                        .HasDatabaseName("IX_ConversationSession_LastAccessed");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("IX_ConversationSession_SessionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ConversationSession_UserId");

                    b.ToTable("ConversationSessions");
                });

            modelBuilder.Entity("MEAI_GPT_API.Models.GroundingFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroundingReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResolvedByCorrection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetrievedSourcesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_GroundingFailure_CreatedAt");

                    b.HasIndex("Plant")
                        .HasDatabaseName("IX_GroundingFailure_Plant");

                    b.HasIndex("ResolvedByCorrection")
                        .HasDatabaseName("IX_GroundingFailure_Resolved");

                    b.ToTable("GroundingFailures");
                });

            modelBuilder.Entity("MEAI_GPT_API.Models.ConversationEntry", b =>
                {
                    b.HasOne("MEAI_GPT_API.Models.ConversationEntry", "ParentConversation")
                        .WithMany("FollowUps")
                        .HasForeignKey("FollowUpToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MEAI_GPT_API.Models.ConversationSession", null)
                        .WithMany("Conversations")
                        .HasForeignKey("SessionId")
                        .HasPrincipalKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentConversation");
                });

            modelBuilder.Entity("MEAI_GPT_API.Models.ConversationEntry", b =>
                {
                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("MEAI_GPT_API.Models.ConversationSession", b =>
                {
                    b.Navigation("Conversations");
                });
#pragma warning restore 612, 618
        }
    }
}
